apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask
  template:
    metadata:
      name: flask
      labels:
        name: flask
    spec:
      containers:
        - name: flask
          image: gcr.io/qp-cloud-coe-tfa-1-2021-02/flask:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ATC_USERNAME
              value: "ANIKET"
            - name: ATC_PASSWORD
              value: "Pass@123"
